### ISSUE TITLE
Agreeing Upon String and Object

### ISSUE THREAD

**Issue by KyleCrampton** [jaspersong/CS4500-SnowyJoe-A1-part2#11]
Chase posted his repo for a String and Object class on piazza, so that we can all come together on the same specs for those classes. Would you all mind adopting those specs/do you have any objections? Link to repo for convenience: https://github.com/chasebish/cwc_object_string

**Comment by jaspersong** [comment]
Updated at commit [d2a560108bad6b08316e6e3d159968b2dadfd160](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/d2a560108bad6b08316e6e3d159968b2dadfd160)
