### ISSUE TITLE
Need Includes

### ISSUE THREAD

**Issue by KyleCrampton** [jaspersong/CS4500-SnowyJoe-A1-part2#12]
Can you all add the appropriate includes to the top of your specs (mainly object.h and string.h as well as cstdlib for size_t). Thanks!

**Comment by jaspersong** [comment]
Fixed in commit [2265349168a64768d1d58e37b0c347ef24cc5a0c](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/2265349168a64768d1d58e37b0c347ef24cc5a0c)
