### ISSUE TITLE
an error will occur?

### ISSUE THREAD

**Issue by ghost** [jaspersong/CS4500-SnowyJoe-A1-part2#13]
There are errno, perror(). and strerror().

You can also just return nullptr. Also, please add tests for "error" testing. I suggest just returning nullptr

**Comment by jaspersong** [comment]
Updated documentation in commit [887d7739afc37af129243e38beb1cb34b9bdf7b8](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/887d7739afc37af129243e38beb1cb34b9bdf7b8)
