### ISSUE TITLE
push methods

### ISSUE THREAD

**Issue by ghost** [jaspersong/CS4500-SnowyJoe-A1-part2#14]
In the description, there should be some checking for whether the queue holds objects or strings.

`  // Pushes a string into the queue in a first in, first out style.
  // Parameter: str  The string to be added to the queue`

**Comment by jaspersong** [comment]
Updated API in commit [8a6ff0e12380b56fad6e25f481690556e2dfd36b](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/8a6ff0e12380b56fad6e25f481690556e2dfd36b)
