### ISSUE TITLE
Tiny Issue in test-queue.cpp

### ISSUE THREAD

**Issue by jjones-99** [jaspersong/CS4500-SnowyJoe-A1-part2#15]
There's a tiny typo in **test-queue.cpp, line 49**:

```
47..........t_true(q2->hash() == q2->hash());
48..........t_false(q2->hash() == q1->hash());
49..........t_true(q2->hash() == q1->hash());         // q1->hash()?
```

The arguments in line 49 are the same as line 48 but using `t_true()` instead of `t_false()`. Based on the symmetry with the `equals()` tests above, I'm assuming this should be testing equality for the hashes of `q2` and `q3`, not `q2` and `q1`.

**Comment by jaspersong** [comment]
Fixed in commit [dbf4f7dd533c8b1902d370bfa7649e70e073155e](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/dbf4f7dd533c8b1902d370bfa7649e70e073155e)
