### ISSUE TITLE
#include in test-queue.cpp

### ISSUE THREAD

**Issue by jjones-99** [jaspersong/CS4500-SnowyJoe-A1-part2#17]
Could you add `#include <stdio.h>` to `test-queue.cpp`?

When we run our implementation with the Dockerfile provided on Piazza, this causes a compilation error because `printf()` is not defined.

**Comment by jjones-99** [comment]
Actually, we just ran it again and now it's not complaining. 🤷‍♂

**Comment by jaspersong** [comment]
Okay. We're closing this issue for now. If it becomes an issue again, feel free to reopen this one.
