### ISSUE TITLE
Removal of get_* Methods?

### ISSUE THREAD

**Issue by KyleCrampton** [jaspersong/CS4500-SnowyJoe-A1-part2#18]
We've been thinking about this a bit, and we were wondering if you all would be okay with removing get_object and get_string? This doesn't seem like typical queue functionality... Let us know if you're comfortable with this!

**Comment by jaspersong** [comment]
We're fine with that, since we understand that it is not mandatory queue functionality. We are removing the functions from the API at commit [0e8ccab5b99549ec2b13ceef2610e1cb4e45a368](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/0e8ccab5b99549ec2b13ceef2610e1cb4e45a368)
