### ISSUE TITLE
Removal of Object tests

### ISSUE THREAD

**Issue by ricardolarios** [jaspersong/CS4500-SnowyJoe-A1-part2#19]
According to [this](https://piazza.com/class/k51bluky59n2jr?cid=377) Piazza post, `test1` in `test_queue.cpp` should be deleted since it's testing the Object implementation instead of just the Queue implementation. Thanks!

**Comment by jaspersong** [comment]
Fixed in commit [cc998d94818c2a92b00e9b1b36c37f5f564b77b2](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/cc998d94818c2a92b00e9b1b36c37f5f564b77b2)
