### ISSUE TITLE
Issue with Test 19 and 20

### ISSUE THREAD

**Issue by ricardolarios** [jaspersong/CS4500-SnowyJoe-A1-part2#20]
https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/blob/0543b780d946ef014440d37595c291ac0e0635f6/test-queue.cpp#L333

In tests 19 and 20, you're calling `t_true` and `t_false` with methods that have a return type of void, which won't compile. Should `push_object` and `push_string` have a return type of bool (i.e. true on success, false on failure) or do you want to change the tests to assert it in another way? Either way is fine.

**Comment by jaspersong** [comment]
Yes. The push methods have a return type of bool. Please refer to commit [8a6ff0e12380b56fad6e25f481690556e2dfd36b](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/8a6ff0e12380b56fad6e25f481690556e2dfd36b)
