### ISSUE TITLE
Add public to class declaration

### ISSUE THREAD

**Issue by KyleCrampton** [jaspersong/CS4500-SnowyJoe-A1-part2#21]
https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/blob/0543b780d946ef014440d37595c291ac0e0635f6/queue.h#L23

Can you all add public here so it reads `class Queue : public Object`? This is causing some issues in test compilation.

**Comment by jaspersong** [comment]
Fixed in commit [de8aeb6a642f7e4d96c16d28600809b8ef80aa7e](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/de8aeb6a642f7e4d96c16d28600809b8ef80aa7e)
