### ISSUE TITLE
Use polymorphism please

### ISSUE THREAD

**Issue by ghost** [jaspersong/CS4500-SnowyJoe-A1-part2#3]
Object *pop_object();
String *pop_string();

Object is a String so just use Object *pop_object(). Unfortunately, templates and macros are not used in CwC so returning Object is good enough. Please fix other methods.

**Comment by jaspersong** [comment]
Hello,

Why do you want to combine the two functions into just a `Object *pop()`? Doing so would mean that you would no longer be sure that the returned object is a string. As a result, you would not be able to call any String-specific functionality without having to do a dynamic cast of the object to a string, which may or may not work, as `void push(Object *)` would not enforce the data to be a string when it is pushed onto the queue, and could possibly crash the program.

**Comment by ghost** [comment]
Pushing String* or Object* are still pointers. They fit into a word size. It's unnecessary to call a String-specific functionality. A queue is just a container so it is up to the user who pop's the data to cast it back.

Do you know a CwC way to return a parameterized type?

**Comment by jaspersong** [comment]
Yes, I understand that it will be possible. However, I do not agree that it is up to the user who pops the data out of the queue to cast it, in case the user had pushed an object that is not a string into the queue.

And I do not know of a CwC way to return a parameterized type, as I have worked with C exclusive libraries whose APIs match the specs we provided to the queue: where you can query for the return type, and then call the appropriate function based off of the queried type.

**Comment by ghost** [comment]
Is there a way to query for a type instead of an enum so that I can possibly do something like:

type my_type = queue.getObjectType
my_type foo = (my_type *) some_object

The use of enums means that I have to do a switch statement over all enums then cast.

**Comment by jaspersong** [comment]
In terms of the C language: no, C does not support that sort of thing.

Here is an example of a very well-known C library that does this sort of thing:
[http://mongoc.org/libbson/current/api.html](http://mongoc.org/libbson/current/api.html)

Look for bson_type_t and bson_iter_t, which provide this sort of functionality.

**Comment by ghost** [comment]
Alright. Thanks
