### ISSUE TITLE
virtual methods

### ISSUE THREAD

**Issue by ghost** [jaspersong/CS4500-SnowyJoe-A1-part2#5]
make all methods virtual except for the constructor

**Comment by jaspersong** [comment]
Fixed in commit [6e23929e1ec8f0c6430ed691ba8f5b8c2d54083e](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/6e23929e1ec8f0c6430ed691ba8f5b8c2d54083e)
