### ISSUE TITLE
include String

### ISSUE THREAD

**Issue by ghost** [jaspersong/CS4500-SnowyJoe-A1-part2#7]
#include "string.h"
Please upload the string header file. The assignment does not specify implementing a String class so it is assumed to be given like the Object class.

**Comment by jaspersong** [comment]
Fixed in commit [5aef201df14d21d9b145e59fe9d8d10f373890e5](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/5aef201df14d21d9b145e59fe9d8d10f373890e5)
