### ISSUE TITLE
String Constructor

### ISSUE THREAD

**Issue by jjones-99** [jaspersong/CS4500-SnowyJoe-A1-part2#8]
The default constructor alone is provided in the spec for `String`. We recommend also including `String(const char* ...)`, or at least some way to give characters to a `String`.

**Comment by jaspersong** [comment]
Fixed in commit [1fe178622b6387ea9fd2616e1d6e09ffe8ab25c4](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/1fe178622b6387ea9fd2616e1d6e09ffe8ab25c4)
