### ISSUE TITLE
Test Suite Issues

### ISSUE THREAD

**Issue by jjones-99** [jaspersong/CS4500-SnowyJoe-A1-part2#9]
Going through the testing suite in `main.cpp`, it looks like there are some errors that you might want to look at:

- Based on the deliverables specified in A1, this file should likely be called `test-queue.cpp`, not `main.cpp`.
- Everything uses `.` notation, but pointers should use `->` notation.
- Missing tests for `hash()` for the various types (since you don't really 'know' the hash value, you can probably just test that if objects are equal their hashes are equal and vice versa).
- In `test4()` (lines 79 and 90), should the index argument to `get_object()` and `get_string()` be 1? 2 would likely be an out-of-bounds error.
- In `test4()` (lines 83 and 94), the length should be 0 after popping the second item.
- In `test5()` (lines 110 and 118), the length should be 2, as `peek()` doesn't remove items.

**Comment by jaspersong** [comment]
Fixed in commit [c580adecd0a559858c20b496f789b895dd852fbe](https://github.com/jaspersong/CS4500-SnowyJoe-A1-part2/commit/c580adecd0a559858c20b496f789b895dd852fbe)
